AlmosBundle_homepage:
    pattern:  /{_locale}
    defaults: { _controller: AlmosBundle:Page:index, _locale: en  }
    requirements:
        _method:  GET

AlmosBundle_about:
    pattern:  /{_locale}/about
    defaults: { _controller:  AlmosBundle:Page:about, _locale: en }
    requirements:
        _method:  GET


AlmosBundle_contact:
    pattern:  /{_locale}/contact
    defaults: { _controller: AlmosBundle:Page:contact, _locale: en }
    requirements:
           _method:  GET|POST


AlmosBundle_question_show:
    pattern:  /{_locale}/{id}/{slug}
    defaults: { _controller: AlmosBundle:Question:show , slug: 'a-day-with-symfony2', _locale: en}
    requirements:
        _method:  GET
        id: \d+


AlmosBundle_comment_create:
    pattern:  /{_locale}/comment/{blog_id}
    defaults: { _controller: AlmosBundle:Comment:create , _locale: en}
    requirements:
        _method:  POST
        blog_id: \d+